// btop/app.jsx — canvas assembly
(function () {
  const { DesignCanvas, DCSection, DCArtboard } = window; const B = window.btop;
  const { Frame, Overview, FocusCPU, FocusProc, Ambient, PortraitOverview, PortraitAmbient } = B.presets;
  const A = ({ id, label, w = 2560, h = 720, notes, children }) => (<DCArtboard id={id} label={label} width={w} height={h + 150}><Frame w={w} h={h} notes={notes}>{children}</Frame></DCArtboard>);
  const S = ({ id, label, w = 2560, h = 720, children }) => <DCArtboard id={id} label={label} width={w} height={h}>{children}</DCArtboard>;
  function App() { return (<DesignCanvas>
    <DCSection id="presets" title="1 · Dashboard presets" subtitle="2560 × 720 · Default Glass theme. btop's five boxes reorganised for 32:9: header strip + four side-by-side boxes. Swipe ← → between presets.">
      <DCArtboard id="p1" label="01 · Overview" width={2560} height={870}><Frame w={2560} h={720} notes={[['Header strip', 'host, macOS, uptime, Xeneon status, sampling (SystemConfiguration + ProcessInfo). Clock 1 s. Battery via IOPowerSources.'], ['cpu', 'host_processor_info total history + per-core grouped P/E (sysctl hw.perflevel). Thermal via ProcessInfo.thermalState. GPU via IOKit AGXAccelerator PerformanceStatistics.'], ['mem', 'host_statistics64 → App/Wired/Compressed/Cached/Free; pressure from DISPATCH_MEMORYPRESSURE. Disks: FileManager volumes + IOBlockStorageDriver stats for R/W.'], ['net', 'getifaddrs deltas per interface; mirrored graph down↑ up↓. RSSI/link from CoreWLAN, ping via SimplePing.'], ['proc', 'proc_listpids + proc_pidinfo, icons via NSWorkspace. Top-7 sorted by CPU; tap row → sheet; tap header → sort; tap title → full list (Focus Processes).'], ['Gestures', 'tap graph → time range · long-press box → edit · swipe bg → preset.']]}><Overview /></Frame></DCArtboard>
      <DCArtboard id="p2" label="02 · Focus CPU" width={2560} height={870}><Frame w={2560} h={720} notes={[['cpu 60 %', '1500 px. History graph shrinks to 200 px to make room for 16 per-core history graphs (8 × 2) — E-cores marked with accent edge.'], ['Per-core', 'each cell 170 × 92: label, live %, 60 s history with ramp.'], ['Right 40 %', 'mem (disks without I/O sparks, single-column legend) + net (no chip row). proc hidden in this preset.'], ['Frequency', 'slot collapsed — not exposed on Apple Silicon.']]}><FocusCPU /></Frame></DCArtboard>
      <DCArtboard id="p3" label="03 · Focus Processes + detail sheet" width={2560} height={870}><Frame w={2560} h={720} notes={[['Full-width table', '9 rows × 44 px, wide column set: icon, name, PID, user, threads, mem spark + value, cpu spark + value.'], ['Selection', 'row highlights (surface2 + accent inset ring); sheet slides in from right, 780 px, glass.'], ['Sheet', 'full command (wrapped mono), 4 stat tiles, 60 s CPU + memory graphs, Terminate / Force Quit…'], ['Destructive', 'Force Quit… is tinted only; real action needs the confirmation step (artboard 07).']]}><FocusProc /></Frame></DCArtboard>
      <DCArtboard id="p4" label="04 · Ambient / Minimal" width={2560} height={870}><Frame w={2560} h={720} notes={[['Clock', 'SF Mono 300 px weight 200, seconds in text3. Date + week + next calendar event (EventKit).'], ['Three sparklines', 'cpu, mem, net ↓ · 420 × 64 · value 36 mono.'], ['Auto-enter', 'after N min idle (Settings › Display). Dims to 60 % and drifts ±4 px every 60 s for burn-in protection.'], ['Exit', 'any tap or activity spike > threshold returns to the last preset.']]}><Ambient /></Frame></DCArtboard>
    </DCSection>
    <DCSection id="states" title="2 · States & interactions" subtitle="Alerts live in the header strip and as an edge glow on the affected box — never modal. Edit mode is done on the touch screen itself.">
      <DCArtboard id="s5" label="05 · Overview · active alerts" width={2560} height={870}><Frame w={2560} h={720} notes={[['Alert strip', 'header centre; chips in crit / warn colour with pulsing dot and age. Max 3, oldest collapses to a count.'], ['Edge glow', 'affected box border + soft outer/inner glow in the alert colour (mem here).'], ['Data', 'pressure Critical, swap 3.8 / 4 GB, Free 0.5 GB; Macintosh HD at 95 %.'], ['Dismiss', 'tap chip → jumps to box; alerts clear automatically when the condition ends.']]}><Overview alert /></Frame></DCArtboard>
      <DCArtboard id="s6" label="06 · Edit mode" width={2560} height={870}><Frame w={2560} h={720} notes={[['Enter', 'long-press any box 0.6 s. Boxes tilt ±0.5° and get a dashed accent outline (static, no wobble animation on OLED).'], ['Handles', '56 px × hide (top-right), ⋮⋮ drag (top-left), corner resize grip. Drag to reorder; neighbours slide.'], ['Toolbar', 'hidden boxes as + chips, Reset, Done. mem shown lifted (being dragged).'], ['Fallback', 'the same layout editor exists in Settings › Layout on the Mac.']]}><Overview edit /></Frame></DCArtboard>
      <DCArtboard id="s7" label="07 · Force Quit confirmation" width={2560} height={870}><Frame w={2560} h={720} notes={[['Confirmation', 'inline card inside the sheet — no modal. Explains consequence in one sentence.'], ['Hold to confirm', 'press-and-hold 1.0 s fills the button; releasing early cancels. Prevents accidental touches on a secondary display.'], ['Cancel', 'equal-weight secondary button, always on the left.'], ['Terminate', 'SIGTERM path uses the same pattern but 0.5 s hold.']]}><FocusProc confirm /></Frame></DCArtboard>
      <DCArtboard id="s8" label="08 · Pickers open + gestures" width={2560} height={870}><Frame w={2560} h={720} notes={[['Time range', 'popover centred on the graph: 1 min / 5 min / 15 min / 1 h. Persists per box.'], ['Interface', 'popover above chip row: Auto (sum en*), Wi-Fi, Ethernet, USB with IP/link sub-line.'], ['Orange callouts', 'annotation only — tap ●, long-press ◉, swipe ⟷.'], ['Preset swipe', 'horizontal swipe on background or header; page dots in header.']]}><Overview pickers /></Frame></DCArtboard>
    </DCSection>
    <DCSection id="themes" title="3 · Themes" subtitle="Same Overview layout, four alternative token sets. Graph ramp, state colours and hairlines all come from semantic tokens.">
      <DCArtboard id="t9" label="09 · OLED Black" width={2560} height={720}><Overview theme="oled" /></DCArtboard>
      <DCArtboard id="t10" label="10 · Nord" width={2560} height={720}><Overview theme="nord" /></DCArtboard>
      <DCArtboard id="t11" label="11 · Daylight" width={2560} height={720}><Overview theme="light" /></DCArtboard>
      <DCArtboard id="t12" label="12 · Tokyo Night" width={2560} height={720}><Overview theme="tokyo" /></DCArtboard>
    </DCSection>
    <DCSection id="portrait" title="4 · Portrait" subtitle="720 × 2560 — the same boxes stacked, 672 px wide. Header becomes a two-line clock + status block.">
      <DCArtboard id="o13" label="13 · Overview portrait" width={720} height={2710}><Frame w={720} h={2560} notes={[['Stack', 'header 100 · cpu 600 · mem 600 · net 480 · proc 668, 16 px gaps.'], ['cpu', 'core bars narrow to 26 px so both groups fit 628 px.'], ['proc', '8 rows; same compact column set as landscape.']]}><PortraitOverview /></Frame></DCArtboard>
      <DCArtboard id="o14" label="14 · Ambient portrait" width={720} height={2710}><Frame w={720} h={2560} notes={[['Clock', '168 px so 14:32 07 fits 672 px.'], ['Sparklines', 'stacked, 300 × 120 each, generous gaps.'], ['Dim', 'shown at 60 % glance brightness.']]}><PortraitAmbient /></Frame></DCArtboard>
    </DCSection>
    <DCSection id="mac" title="5 · Mac-side UI" subtitle="Native NSMenu dropdown and a compact Settings window (720 × 480) with six tabs.">
      <DCArtboard id="m15" label="15 · Menu-bar dropdown · 280 px" width={640} height={560}><B.mac.MenuBarDropdown /></DCArtboard>
      <DCArtboard id="m16a" label="16a · Settings · Layout" width={720} height={480}><B.mac.SettingsLayout /></DCArtboard>
      <DCArtboard id="m16b" label="16b · Settings · Theme" width={720} height={480}><B.mac.SettingsTheme /></DCArtboard>
    </DCSection>
    <DCSection id="lib" title="6 · Component library & tokens" subtitle="Every element with pixel dimensions and type sizes; colour tokens for all themes; type, spacing, thresholds, motion, fallbacks.">
      <DCArtboard id="c17" label="17 · Component library" width={2560} height={1100}><B.sheet.ComponentSheet /></DCArtboard>
      <DCArtboard id="c18" label="18 · Design tokens" width={2560} height={900}><B.sheet.TokenSheet /></DCArtboard>
    </DCSection>
  </DesignCanvas>); }
  ReactDOM.createRoot(document.getElementById('root')).render(<App />);
})();
