// btop/mac.jsx — Mac-side UI: menu-bar dropdown + Settings window
(function () {
  const B = window.btop; const { themes, sans, mono, ThemeCtx } = B; const { Toggle, num, HistoryGraph } = B.ui;
  const M = { bg: 'rgba(40,40,44,0.92)', text: 'rgba(255,255,255,0.92)', text2: 'rgba(255,255,255,0.55)', sep: 'rgba(255,255,255,0.12)', hi: '#3478f6', win: '#2b2b2e', panel: '#1e1e21', hair: 'rgba(255,255,255,0.1)' };
  const Item = ({ children, check, sub, kbd, hi, arrow }) => (<div style={{ height: 26, display: 'flex', alignItems: 'center', gap: 8, padding: '0 10px 0 8px', margin: '0 5px', borderRadius: 5, background: hi ? M.hi : 'transparent', color: M.text, fontFamily: sans, fontSize: 13 }}><span style={{ width: 12, textAlign: 'center', fontSize: 11 }}>{check ? '✓' : ''}</span><span style={{ flex: 1 }}>{children}</span>{sub && <span style={{ color: hi ? 'rgba(255,255,255,0.8)' : M.text2, fontSize: 12 }}>{sub}</span>}{kbd && <span style={{ color: hi ? 'rgba(255,255,255,0.8)' : M.text2, ...num, fontSize: 12 }}>{kbd}</span>}{arrow && <span style={{ color: hi ? '#fff' : M.text2, fontSize: 10 }}>▶</span>}</div>);
  const Sep = () => <div style={{ height: 1, background: M.sep, margin: '5px 14px' }} />;
  function Menu({ w, children, style }) { return <div style={{ width: w, background: M.bg, backdropFilter: 'blur(40px)', borderRadius: 10, padding: '5px 0', boxShadow: '0 12px 40px rgba(0,0,0,.5), 0 0 0 0.5px rgba(255,255,255,0.18)', ...style }}>{children}</div>; }

  function MenuBarDropdown() { return (<div style={{ width: 640, height: 560, background: 'linear-gradient(160deg,#5b6b8c,#2e3550)', position: 'relative', fontFamily: sans, borderRadius: 12, overflow: 'hidden' }}>
    <div style={{ height: 30, background: 'rgba(30,30,36,0.7)', backdropFilter: 'blur(20px)', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 16, padding: '0 14px', color: '#fff', fontSize: 13 }}><span style={{ padding: '2px 6px', borderRadius: 5, background: 'rgba(255,255,255,0.22)' }}>▤</span><span>⌂</span><span>◔</span><span style={{ ...num }}>Thu 4 Sep  14:32</span></div>
    <Menu w={280} style={{ position: 'absolute', top: 34, right: 330 }}>
      <div style={{ padding: '6px 14px 8px', display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ width: 8, height: 8, borderRadius: 4, background: '#30d158', boxShadow: '0 0 6px #30d158' }} /><span style={{ color: M.text, fontSize: 13, fontWeight: 600 }}>Xeneon Edge</span><span style={{ color: M.text2, fontSize: 12 }}>Connected · 2560 × 720</span></div>
      <div style={{ padding: '0 14px 8px', display: 'flex', gap: 14, ...num, fontSize: 12, color: M.text2 }}><span>cpu <b style={{ color: M.text }}>34%</b></span><span>mem <b style={{ color: M.text }}>59%</b></span><span>↓ <b style={{ color: M.text }}>12.4</b> MB/s</span></div><Sep />
      <Item check>Show Dashboard</Item><Item kbd="⌥⌘X">Dashboard on Xeneon Edge</Item><Sep />
      <Item hi arrow sub="Overview">Preset</Item><Item arrow sub="Default Glass">Theme</Item><Item arrow sub="Xeneon Edge">Target Display</Item><Item arrow sub="1 s">Sampling</Item><Sep />
      <Item check>Launch at Login</Item><Item>Glance mode after 5 min</Item><Sep />
      <Item kbd="⌘,">Settings…</Item><Item kbd="⌘Q">Quit XeneonWidgets</Item></Menu>
    <Menu w={220} style={{ position: 'absolute', top: 126, right: 108 }}><Item check>Overview</Item><Item>Focus CPU</Item><Item>Focus Processes</Item><Item>Ambient</Item><Sep /><Item sub="auto">Portrait Overview</Item><Item sub="auto">Portrait Ambient</Item><Sep /><Item>Edit Layout on Display…</Item></Menu>
    <div style={{ position: 'absolute', left: 20, bottom: 18, color: 'rgba(255,255,255,0.7)', fontSize: 12, maxWidth: 300, lineHeight: 1.4 }}>Native NSMenu. Live values in the header row refresh at the sampling interval. Submenus follow system behaviour; ⌥⌘X toggles the dashboard globally.</div></div>); }

  // Settings window
  const tabs = [['Display', '▭'], ['Layout', '▦'], ['Sampling', '◔'], ['Theme', '◐'], ['Processes', '≣'], ['About', 'ⓘ']];
  function Win({ tab, children }) { return (<div style={{ width: 720, height: 480, background: M.win, borderRadius: 12, overflow: 'hidden', fontFamily: sans, color: M.text, display: 'flex', flexDirection: 'column', boxShadow: '0 0 0 0.5px rgba(255,255,255,0.15)' }}>
    <div style={{ height: 52, display: 'flex', alignItems: 'center', padding: '0 12px', gap: 8, borderBottom: `1px solid ${M.hair}`, background: '#323236' }}><div style={{ display: 'flex', gap: 8, marginRight: 12 }}>{['#ff5f57', '#febc2e', '#28c840'].map(c => <span key={c} style={{ width: 12, height: 12, borderRadius: 6, background: c }} />)}</div><span style={{ fontSize: 13, fontWeight: 600, marginRight: 'auto' }}>XeneonWidgets Settings</span></div>
    <div style={{ height: 64, display: 'flex', justifyContent: 'center', gap: 6, alignItems: 'center', borderBottom: `1px solid ${M.hair}`, background: '#2e2e32' }}>{tabs.map(([l, g]) => <div key={l} style={{ width: 76, height: 52, borderRadius: 8, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 2, background: l === tab ? 'rgba(255,255,255,0.1)' : 'transparent', color: l === tab ? M.text : M.text2, fontSize: 11 }}><span style={{ fontSize: 20, color: l === tab ? '#5ea0ff' : M.text2 }}>{g}</span>{l}</div>)}</div>
    <div style={{ flex: 1, padding: 20, display: 'flex', gap: 20 }}>{children}</div></div>); }
  const Row = ({ k, v, last }) => <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', height: 36, borderBottom: last ? 'none' : `1px solid ${M.hair}`, fontSize: 13 }}><span>{k}</span>{v}</div>;
  const Select = ({ v }) => <span style={{ background: '#3a3a3f', border: '1px solid rgba(255,255,255,0.15)', borderRadius: 6, padding: '3px 8px 3px 10px', fontSize: 12, display: 'inline-flex', gap: 8 }}>{v}<span style={{ color: M.text2 }}>⌃</span></span>;

  function SettingsLayout() { const boxes = [['cpu', 30], ['mem', 24], ['net', 19], ['proc', 27]]; return (<Win tab="Layout">
    <div style={{ width: 200, display: 'flex', flexDirection: 'column', gap: 4 }}>{['Overview', 'Focus CPU', 'Focus Processes', 'Ambient', 'Portrait Overview', 'Portrait Ambient'].map((p, i) => <div key={p} style={{ height: 32, borderRadius: 6, padding: '0 10px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: i === 0 ? M.hi : 'transparent', fontSize: 13 }}>{p}{i === 0 && <span style={{ fontSize: 11, opacity: 0.8 }}>active</span>}</div>)}<div style={{ marginTop: 'auto', display: 'flex', gap: 6 }}><span style={{ width: 28, height: 24, borderRadius: 5, background: '#3a3a3f', textAlign: 'center', lineHeight: '24px' }}>+</span><span style={{ width: 28, height: 24, borderRadius: 5, background: '#3a3a3f', textAlign: 'center', lineHeight: '24px' }}>−</span></div></div>
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 14 }}><div style={{ fontSize: 12, color: M.text2 }}>Overview · 2560 × 720 · drag to reorder, uncheck to hide</div>
      <div style={{ height: 96, background: '#141416', borderRadius: 8, padding: 6, display: 'flex', gap: 4 }}>{boxes.map(([b, w]) => <div key={b} style={{ flex: w, background: '#2a2a2e', borderRadius: 5, border: '1px solid rgba(255,255,255,0.12)', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', padding: 6, ...num, fontSize: 10, color: M.text2 }}><span>{b}</span><span style={{ fontSize: 9 }}>⋮⋮</span></div>)}</div>
      <div style={{ display: 'flex', flexDirection: 'column' }}>{[['cpu · history, cores, GPU', true], ['mem · memory + disks', true], ['net · mirrored graph', true], ['proc · top 7', true], ['battery (header)', true], ['clock (header)', true]].map(([k, on], i, a) => <Row key={k} k={k} v={<Toggle on={on} />} last={i === a.length - 1} />)}</div>
      <div style={{ marginTop: 'auto', display: 'flex', gap: 8, justifyContent: 'flex-end' }}><span style={{ padding: '5px 12px', borderRadius: 6, background: '#3a3a3f', fontSize: 12 }}>Reset to Default</span><span style={{ padding: '5px 12px', borderRadius: 6, background: M.hi, fontSize: 12 }}>Edit on Display…</span></div></div></Win>); }

  function SettingsTheme() { return (<Win tab="Theme"><div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 14 }}>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: 10 }}>{Object.values(themes).map(t => (<div key={t.id} style={{ borderRadius: 10, padding: 4, border: `2px solid ${t.id === 'default' ? M.hi : 'transparent'}` }}><ThemeCtx.Provider value={t}><div style={{ height: 70, borderRadius: 7, background: t.bg, padding: 6, display: 'flex', gap: 4 }}>{[0, 1].map(i => <div key={i} style={{ flex: 1, background: t.surface, borderRadius: 4, border: `1px solid ${t.hairline}`, padding: 4, display: 'flex', flexDirection: 'column', gap: 3 }}><div style={{ height: 3, width: '40%', background: t.text3, borderRadius: 2 }} /><HistoryGraph values={B.data.cpu.hist.slice(0, 40)} w={48} h={30} grid={false} strokeWidth={1.2} /></div>)}</div></ThemeCtx.Provider><div style={{ fontSize: 11, textAlign: 'center', marginTop: 6, color: t.id === 'default' ? M.text : M.text2 }}>{t.name}</div></div>))}</div>
    <div style={{ display: 'flex', flexDirection: 'column' }}><Row k="Follow system appearance" v={<Toggle on={false} />} /><Row k="Graph ramp" v={<div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: M.text2 }}><span style={{ width: 120, height: 10, borderRadius: 5, background: `linear-gradient(90deg, ${themes.default.rampLow}, ${themes.default.rampMid}, ${themes.default.rampHigh})` }} />low → mid → high</div>} /><Row k="Thresholds" v={<span style={{ ...num, fontSize: 12, color: M.text2 }}>ok &lt; 50 · warn &lt; 80 · crit ≥ 80</span>} /><Row k="Glance mode dim level" v={<Select v="60 %" />} /><Row k="Burn-in shift" v={<Toggle on />} last /></div>
    <div style={{ marginTop: 'auto', fontSize: 11, color: M.text2 }}>Themes are JSON files in ~/Library/Application Support/XeneonWidgets/Themes. Import… supports btop .theme files (colour keys are mapped to semantic tokens).</div></div></Win>); }

  B.mac = { MenuBarDropdown, SettingsLayout, SettingsTheme };
})();
