// btop/sheet.jsx — component library + design tokens artboards
(function () {
  const B = window.btop; const { themes, ThemeCtx, useTheme, sans, mono, data: D, type, space } = B;
  const { HistoryGraph, MirrorGraph, Spark, Box, Big, Pill, Chip, ChipRow, CoreBars, SegBar, DiskRow, ProcRow, ProcHead, BatteryPill, AlertStrip, Btn, num } = B.ui;
  const t0 = themes.default;
  const Spec = ({ title, dims, children, w }) => (<div style={{ display: 'flex', flexDirection: 'column', gap: 12, width: w }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', borderBottom: `1px solid ${t0.hairline}`, paddingBottom: 8 }}><span style={{ fontFamily: sans, fontSize: 16, fontWeight: 600, color: t0.text }}>{title}</span><span style={{ ...num, fontSize: 12, color: '#ff7a3d' }}>{dims}</span></div>{children}</div>);

  function ComponentSheet() { const p = D.procs[0]; const segs = [{ k: 'App', v: 12.8, c: t0.rampHigh }, { k: 'Wired', v: 4.1, c: t0.rampMid }, { k: 'Compressed', v: 2.3, c: t0.up }, { k: 'Cached files', v: 6.4, c: t0.rampLow }, { k: 'Free', v: 10.4, c: t0.text3 }];
    return (<ThemeCtx.Provider value={t0}><div style={{ width: 2560, height: 1100, boxSizing: 'border-box', padding: 40, background: t0.bg, display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gridAutoRows: 'min-content', gap: '40px 48px', fontFamily: sans, color: t0.text }}>
      <Spec title="Box header (btop nod)" dims="title 16 mono +2.4 tracking · value 22 mono 500 · pad 22 · r 20"><Box title="cpu" meta="Apple M3 Max · 12P + 4E" value="34%" valueColor={t0.ok} w={560} h={110}><span style={{ fontFamily: sans, fontSize: 13, color: t0.text3 }}>surface rgba(255,255,255,.055) · hairline .09 · blur 30</span></Box></Spec>
      <Spec title="Big-number tile" dims="72 / 56 / 34 mono 600 · tabular · unit 36% of size"><div style={{ display: 'flex', gap: 40, alignItems: 'flex-end' }}><Big v={34} unit="%" color={t0.ok} label="total · 16 cores" /><Big v={59} unit="%" size={56} color={t0.warn} label="used" /><Big v={18} unit="%" size={34} label="GPU" /><Big v="12.4" unit="MB/s" size={36} label="↓ download" /></div></Spec>
      <Spec title="History graph · 3-stop ramp" dims="h 200 · stroke 2 · fill .28→.02 · thresholds 50/80 dashed"><HistoryGraph values={D.cpu.hist} w={560} h={160} /><div style={{ display: 'flex', alignItems: 'center', gap: 12, fontSize: 13, color: t0.text3 }}><span style={{ width: 160, height: 10, borderRadius: 5, background: `linear-gradient(90deg, ${t0.rampLow}, ${t0.rampMid}, ${t0.rampHigh})` }} />Y position drives colour: 0 % low · 50 % mid · 100 % high</div></Spec>
      <Spec title="Mirrored net graph" dims="down above / up below · h 200 · accent + up colour"><MirrorGraph down={D.net.down} up={D.net.up} w={560} h={160} /></Spec>
      <Spec title="Per-core mini bars" dims="bar 32 × 96 · gap 8 · r 6 · value 12 mono"><div style={{ display: 'flex', gap: 24 }}><CoreBars values={D.cpu.pNow.slice(0, 8)} label="8 of 12 P-cores" /><CoreBars values={D.cpu.eNow} label="4 E-cores" /></div></Spec>
      <Spec title="Memory segment bar + legend" dims="h 14 · r 7 · gap 2 · legend 15/15 mono"><SegBar segs={segs} /><B.ui.Legend segs={segs} cols={3} /></Spec>
      <Spec title="Disk row" dims="h 56 · name 16/500 · bar 6 · R/W sparks 70 × 22"><div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><DiskRow d={D.disks[0]} /><DiskRow d={D.disksCrit[0]} crit /></div></Spec>
      <Spec title="Process row" dims="h 54 · icon 28 r 7 · name 17/500 · cpu 17/600 state-coloured"><ProcHead cols="28px 1fr 60px 96px 92px 76px 40px" /><ProcRow p={p} cols="28px 1fr 60px 96px 92px 76px 40px" /><ProcRow p={D.procs[1]} cols="28px 1fr 60px 96px 92px 76px 40px" selected /></Spec>
      <Spec title="Battery pill + status pills" dims="h 40 r 20 · pill h 32 r 16 · dot 8 + glow"><div style={{ display: 'flex', gap: 16, alignItems: 'center', flexWrap: 'wrap' }}><BatteryPill b={D.sys.battery} /><Pill color={t0.ok}>Thermal · Nominal</Pill><Pill color={t0.warn}>Pressure · Warning</Pill><Pill color={t0.crit}>Pressure · Critical</Pill></div></Spec>
      <Spec title="Alert strip" dims="h 40 · 18 % tint · 45 % border · dot pulses 1.6 s (only motion allowed)"><AlertStrip alerts={[{ level: 'crit', text: 'Memory pressure · Critical', since: '2m 14s' }, { level: 'warn', text: 'CPU pegged · 30 s', since: '31s' }]} /></Spec>
      <Spec title="Chip row · touch filter" dims="h 56 min tap · r 14 · 16/600 · selected = text on inverse"><ChipRow items={[{ id: 'all', label: 'All' }, { id: 'apps', label: 'Apps' }, { id: 'bg', label: 'Background' }, { id: 'sys', label: 'System' }, { id: 'hot', label: 'High CPU' }]} active="apps" /></Spec>
      <Spec title="Buttons + tap targets" dims="h 56 r 16 · 18/600 · destructive = crit tint until confirm"><div style={{ display: 'flex', gap: 12 }}><Btn>Cancel</Btn><Btn kind="primary">Done</Btn><Btn kind="destructive">Force Quit</Btn><div style={{ width: 56, height: 56, borderRadius: 28, border: `2px dashed ${t0.accent}`, display: 'flex', alignItems: 'center', justifyContent: 'center', ...num, fontSize: 11, color: t0.accent }}>56</div></div></Spec>
    </div></ThemeCtx.Provider>); }

  function TokenSheet() { const keys = ['bg', 'surface', 'surface2', 'hairline', 'text', 'text2', 'text3', 'rampLow', 'rampMid', 'rampHigh', 'accent', 'up', 'ok', 'warn', 'crit'];
    const Sw = ({ c, bg }) => <div style={{ width: 44, height: 28, borderRadius: 6, background: c, border: '1px solid rgba(255,255,255,0.12)', boxShadow: bg ? 'none' : `inset 0 0 0 1px rgba(0,0,0,0.2)` }} />;
    const H = ({ children }) => <div style={{ fontFamily: sans, fontSize: 16, fontWeight: 600, color: t0.text, borderBottom: `1px solid ${t0.hairline}`, paddingBottom: 8, marginBottom: 14 }}>{children}</div>;
    return (<div style={{ width: 2560, height: 900, boxSizing: 'border-box', padding: 40, background: t0.bg, display: 'grid', gridTemplateColumns: '1.6fr 1fr 1fr', gap: 48, fontFamily: sans, color: t0.text }}>
      <div><H>Colour tokens · 5 themes</H><div style={{ display: 'grid', gridTemplateColumns: '150px repeat(5, 1fr)', rowGap: 6, columnGap: 12, alignItems: 'center' }}><span /> {Object.values(themes).map(t => <span key={t.id} style={{ fontSize: 13, color: t0.text2, fontWeight: 600 }}>{t.name}</span>)}
        {keys.map(k => [<span key={k} style={{ ...num, fontSize: 13, color: t0.text3 }}>{k}</span>, ...Object.values(themes).map(t => <div key={t.id + k} style={{ display: 'flex', alignItems: 'center', gap: 8, background: t.bg, padding: 4, borderRadius: 8 }}><Sw c={t[k]} bg={k === 'bg'} /><span style={{ ...num, fontSize: 10, color: t.text3, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{t[k]}</span></div>)])}</div></div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}><div><H>Type scale · SF Pro / SF Mono (tabular)</H>{[['display', 300, 'ambient clock · SF Mono 200'], ['big', 72, 'box hero number · Mono 600'], ['num', 36, 'rates, sheet stats · Mono 600'], ['h', 22, 'box value (top-right) · Mono 500'], ['body', 17, 'process name · Pro 500'], ['small', 15, 'meta, labels · Pro 400'], ['micro', 13, 'legends, R/W · Mono 400']].map(([k, s, d]) => <div key={k} style={{ display: 'flex', alignItems: 'baseline', gap: 16, height: 46, borderBottom: `1px solid ${t0.hairline}` }}><span style={{ ...num, fontSize: Math.min(s, 40), color: t0.text, width: 90 }}>{k === 'display' ? '14' : k === 'big' ? '34%' : 'Aa 12'}</span><span style={{ ...num, fontSize: 13, color: '#ff7a3d', width: 60 }}>{s} px</span><span style={{ fontSize: 13, color: t0.text3 }}>{k} · {d}</span></div>)}</div>
        <div><H>Graph thresholds & state colour</H><div style={{ display: 'flex', flexDirection: 'column', gap: 8, fontSize: 14, color: t0.text2 }}>{[['CPU / GPU / core', '< 50 ok · < 80 warn · ≥ 80 crit'], ['Memory', '< 70 ok · < 90 warn · ≥ 90 crit — pressure state overrides'], ['Disk', '< 80 ok · < 90 warn · ≥ 90 crit (alert at 95)'], ['Process CPU', '< 10 neutral · < 25 warn · ≥ 25 crit'], ['Thermal', 'Nominal ok · Fair warn · Serious / Critical crit']].map(([k, v]) => <div key={k} style={{ display: 'flex', gap: 12 }}><span style={{ width: 130, color: t0.text3 }}>{k}</span><span style={num}>{v}</span></div>)}</div></div></div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}><div><H>Spacing & radii</H><div style={{ display: 'flex', flexDirection: 'column', gap: 8, fontSize: 14, color: t0.text2 }}>{[['outer padding', 24], ['box gap', 16], ['box padding', 22], ['inner gap', 16 / 12], ['box radius', 20], ['sheet / popover radius', 24 / 18], ['chip radius', 14], ['button radius', 16], ['min tap target', 56], ['header strip', 56], ['hairline', 1]].map(([k, v]) => <div key={k} style={{ display: 'flex', justifyContent: 'space-between', borderBottom: `1px solid ${t0.hairline}`, padding: '4px 0' }}><span style={{ color: t0.text3 }}>{k}</span><span style={num}>{typeof v === 'number' && v < 2 ? '16 / 12' : v} px</span></div>)}</div></div>
        <div><H>Motion & glance mode</H><div style={{ fontSize: 14, color: t0.text2, lineHeight: 1.5, display: 'flex', flexDirection: 'column', gap: 6 }}><span>Graphs scroll left at sampling rate, linear, no easing.</span><span>Numbers tween 240 ms ease-out; colours cross-fade 400 ms.</span><span>Preset swipe: 320 ms spring (0.8 damping), whole screen slides.</span><span>Alert dot is the only pulse (1.6 s). No glow, no bounce.</span><span>Glance: after N min idle → brightness 60 %, layout drifts ±4 px every 60 s.</span></div></div>
        <div><H>Fallbacks (not obtainable)</H><div style={{ fontSize: 14, color: t0.text2, lineHeight: 1.5 }}>Per-core clock → row shows "n/a on Apple Silicon" in text3; hidden entirely when the KV row collapses. SMC temperature → thermal pressure pill is first-class; a temperature pill appears beside it only on Intel Macs.</div></div></div>
    </div>); }

  B.sheet = { ComponentSheet, TokenSheet };
})();
