import XeneonWidgetsCore

func runDashboardModelTests() {
    expectEqual(Preset.ambient.next, .overview, "preset wraps forward")
    expectEqual(Preset.overview.previous, .ambient, "preset wraps backward")
    expectEqual(Preset.overview.next, .focusCPU, "overview next")
    expectEqual(Preset.focusCPU.next, .focusProcesses, "focusCPU next")
    expectEqual(Preset.focusProcesses.next, .ambient, "focusProcesses next")
    expectEqual(Preset.overview.index, 0, "overview index")
    expectEqual(Preset.ambient.index, 3, "ambient index")
    expectEqual(Preset.overview.title, "Overview", "overview title")
    expectEqual(Preset.focusCPU.title, "Focus CPU", "focusCPU title")
    expectEqual(Preset.focusProcesses.title, "Focus Processes", "focusProcesses title")
    expectEqual(Preset.ambient.title, "Ambient", "ambient title")

    expectEqual(BoxID.cpu.title, "cpu", "cpu title")
    expectEqual(BoxID.mem.title, "mem", "mem title")
    expectEqual(BoxID.net.title, "net", "net title")
    expectEqual(BoxID.proc.title, "proc", "proc title")
    expectEqual(BoxID.gpu.title, "gpu", "gpu title")
    expectEqual(BoxID.battery.title, "battery", "battery title")
    expectEqual(BoxID.clock.title, "clock", "clock title")
    expectEqual(BoxID.cpu.displayName, "CPU", "cpu display")
    expectEqual(BoxID.mem.displayName, "Memory", "mem display")
    expectEqual(BoxID.net.displayName, "Network", "net display")
    expectEqual(BoxID.proc.displayName, "Processes", "proc display")
    expectEqual(BoxID.gpu.displayName, "GPU", "gpu display")
    expectEqual(BoxID.battery.displayName, "Battery", "battery display")
    expectEqual(BoxID.clock.displayName, "Clock", "clock display")

    expectEqual(TimeRange.oneMinute.label, "1 min", "1 min label")
    expectEqual(TimeRange.fiveMinutes.label, "5 min", "5 min label")
    expectEqual(TimeRange.fifteenMinutes.label, "15 min", "15 min label")
    expectEqual(TimeRange.oneHour.label, "1 h", "1 h label")
    expectEqual(TimeRange.oneHour.sampleCount(at: .one), 3600, "1 h at 1 s")
    expectEqual(TimeRange.oneMinute.sampleCount(at: .five), 12, "1 min at 5 s")

    expectEqual(SamplingInterval.half.label, "0.5 s sampling", "half label")
    expectEqual(SamplingInterval.one.label, "1 s sampling", "one label")
    expectEqual(SamplingInterval.two.label, "2 s sampling", "two label")
    expectEqual(SamplingInterval.five.label, "5 s sampling", "five label")
    expectEqual(SamplingInterval.half.menuLabel, "0.5 s", "half menu")
    expectEqual(SamplingInterval.one.menuLabel, "1 s", "one menu")
    expectEqual(SamplingInterval.two.menuLabel, "2 s", "two menu")
    expectEqual(SamplingInterval.five.menuLabel, "5 s", "five menu")
    expectEqual(SamplingInterval.half.historyCapacity, 7200, "half history")
    expectEqual(SamplingInterval.one.historyCapacity, 3600, "one history")
    expectEqual(SamplingInterval.two.historyCapacity, 1800, "two history")
    expectEqual(SamplingInterval.five.historyCapacity, 720, "five history")
}
